environment = "staging"

[http]

[[http.server]]
listen = ["80"]
serverName = ["inventory-staging.sdkwork.com", "inventory-staging.birdcoder.com", "inventory-staging.dtupay.com", "inventory-staging.sdkwork.cn", "inventory-staging.birdcoder.cn", "inventory-staging.dtupay.cn", "inventory-staging.skubc.com", "inventory-staging.skubc.cn", "inventory-staging.zowalk.com", "inventory-staging.zowalk.cn", "inventory-staging.offer86.com", "inventory-staging.offer86.cn", "inventory-staging.86offer.com", "inventory-staging.86offer.cn"]
include = ["snippets/gateway-locations.nonproduction.conf"]

